### ISSUE TITLE
Important

### ISSUE THREAD

**Issue by RyanRMurray** [dixonary/aoc-2019#4]
https://github.com/dixonary/aoc-2019/blob/b1ce082447279cfed6eefaa0cc3584e98c86053e/4/Solution.hs#L83

Unsafe bad :[

**Comment by dixonary** [comment]
The only thing better than a bad guy with an `unsafePerformIO` is a good guy with an `unsafePerformIO`

**Comment by mbg** [comment]
I also have this issue
